on:
  push:
    branches:
      - main
  pull_request:
name: Main Build
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
      - name: Cache local Maven repository
        uses: actions/cache@v3.0.2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build, Test
        run: ./mvnw clean package --no-transfer-progress
